name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to github container registry

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_PAT }} 
          repository: ${{ github.repository_owner }}/near-wallet

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags:   ghcr.io/user/app:latest
        

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
    